// src/App.tsx
import React from 'react';
import './App.css';

function App() {
    return (
        <div className="section">
            <div className="container">
                <div className="card mt-4">
                    <header className="card-header">
                        <p className="card-header-title">
                            Firenote 🔥
                        </p>
                    </header>
                    <div className="card-content">
                        <div className="control">
                            <textarea className="textarea" rows={10}/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default App;

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'firenote 🔥';
  isLoading = false;

  onChange(text: string): void {
    this.isLoading = true;
    setTimeout(() => {
      this.isLoading = false;
      console.log('saved', text);
    }, 500);
  }
}

<div class="container">
  <div class="card mt-4">
    <header class="card-header">
      <p class="card-header-title">
        {{title}}
      </p>
    </header>
    <div class="card-content">
      <app-texteditor [isLoading]="isLoading" (changed)="onChange($event)"></app-texteditor>
    </div>
  </div>
</div>
